---
#
# Ansible managed
#
repository:
  description: Install and configure openvpn server or client on your system.
  homepage: https://buluma.github.io/
  topics: openvpn, networking, ansible, molecule, playbook
